In [ ]:
import pandas as pd
import numpy as np
ori_data = pd.read_csv('ETTh1.csv', sep=',')

ori_data.rename(columns={'date': 'Timestamp'}, inplace=True)
ori_data['Timestamp'] = pd.to_datetime(ori_data["Timestamp"])


h = ori_data['Timestamp'].dt.hour
ori_data['hour_sin'] = np.sin(2*np.pi * h / 24)
ori_data['hour_cos'] = np.cos(2*np.pi * h / 24)    
ori_data['month_sin'] = np.sin(2 * np.pi * ori_data['Timestamp'].dt.month / 12)
ori_data['month_cos'] = np.cos(2 * np.pi * ori_data['Timestamp'].dt.month / 12)
ori_data['day_of_week_sin'] = np.sin(2 * np.pi * ori_data['Timestamp'].dt.dayofweek / 7)
ori_data['day_of_week_cos'] = np.cos(2 * np.pi * ori_data['Timestamp'].dt.dayofweek / 7)


ori_data.drop(columns=['Timestamp'], inplace=True)

column_to_move = 'OT'
ori_data = ori_data[[col for col in ori_data.columns if col != column_to_move] + [column_to_move]]
ori_data.to_csv('ETTh1_energy_data.csv', index=False)

In [2]:
ori_data

,HUFL,HULL,MUFL,MULL,LUFL,LULL,hour_sin,hour_cos,month_sin,month_cos,day_of_week_sin,day_of_week_cos,OT
0,5.827,2.009,1.599,0.462,4.203,1.340,0.000000,1.000000e+00,-5.000000e-01,-0.866025,-0.433884,-0.900969,30.531000
1,5.693,2.076,1.492,0.426,4.142,1.371,0.258819,9.659258e-01,-5.000000e-01,-0.866025,-0.433884,-0.900969,27.787001
2,5.157,1.741,1.279,0.355,3.777,1.218,0.500000,8.660254e-01,-5.000000e-01,-0.866025,-0.433884,-0.900969,27.787001
3,5.090,1.942,1.279,0.391,3.807,1.279,0.707107,7.071068e-01,-5.000000e-01,-0.866025,-0.433884,-0.900969,25.044001
4,5.358,1.942,1.492,0.462,3.868,1.279,0.866025,5.000000e-01,-5.000000e-01,-0.866025,-0.433884,-0.900969,21.948000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17415,-1.674,3.550,-5.615,2.132,3.472,1.523,-0.707107,-7.071068e-01,1.224647e-16,-1.000000,0.781831,0.623490,10.904000
17416,-5.492,4.287,-9.132,2.274,3.533,1.675,-0.866025,-5.000000e-01,1.224647e-16,-1.000000,0.781831,0.623490,11.044000
17417,2.813,3.818,-0.817,2.097,3.716,1.523,-0.965926,-2.588190e-01,1.224647e-16,-1.000000,0.781831,0.623490,10.271000
17418,9.243,3.818,5.472,2.097,3.655,1.432,-1.000000,-1.836970e-16,1.224647e-16,-1.000000,0.781831,0.623490,9.778000
17419,10.114,3.550,6.183,1.564,3.716,1.462,-0.965926,2.588190e-01,1.224647e-16,-1.000000,0.781831,0.623490,9.567000

In [3]:
import pandas as pd

df = pd.read_csv('ETTh1_energy_data.csv')
n = len(df)
train_end = int(n * 0.85)
X_train = df.iloc[:train_end]
X_train.to_csv('ETTh1_energy_data.csv', index=False)

In [4]:
len(X_train.columns)

13

In [5]:
X_train

,HUFL,HULL,MUFL,MULL,LUFL,LULL,hour_sin,hour_cos,month_sin,month_cos,day_of_week_sin,day_of_week_cos,OT
0,5.827,2.009,1.599,0.462,4.203,1.340,0.000000,1.000000e+00,-0.5,-8.660254e-01,-0.433884,-0.900969,30.531000
1,5.693,2.076,1.492,0.426,4.142,1.371,0.258819,9.659258e-01,-0.5,-8.660254e-01,-0.433884,-0.900969,27.787001
2,5.157,1.741,1.279,0.355,3.777,1.218,0.500000,8.660254e-01,-0.5,-8.660254e-01,-0.433884,-0.900969,27.787001
3,5.090,1.942,1.279,0.391,3.807,1.279,0.707107,7.071068e-01,-0.5,-8.660254e-01,-0.433884,-0.900969,25.044001
4,5.358,1.942,1.492,0.462,3.868,1.279,0.866025,5.000000e-01,-0.5,-8.660254e-01,-0.433884,-0.900969,21.948000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14802,9.645,1.674,6.538,0.675,3.168,0.609,-1.000000,-1.836970e-16,1.0,6.123234e-17,-0.433884,-0.900969,6.613000
14803,9.578,1.273,6.219,0.320,3.381,0.609,-0.965926,2.588190e-01,1.0,6.123234e-17,-0.433884,-0.900969,5.698000
14804,10.985,2.813,7.427,1.492,3.655,0.883,-0.866025,5.000000e-01,1.0,6.123234e-17,-0.433884,-0.900969,5.487000
14805,11.588,2.880,8.209,1.564,3.350,0.822,-0.707107,7.071068e-01,1.0,6.123234e-17,-0.433884,-0.900969,5.135000
14806,11.588,3.684,8.280,2.061,2.985,0.853,-0.500000,8.660254e-01,1.0,6.123234e-17,-0.433884,-0.900969,5.346000